export interface ConcernItem {
  concern: string
  answer: string
}

export interface TeenetPageContent {
  meta: {
    title: string
    description: string
  }
  title: string
  backLink: string
  whatIs: {
    title: string
    body: string[]
  }
  howProtects: {
    title: string
    hardware: {
      title: string
      body: string[]
    }
    keys: {
      title: string
      body: string[]
    }
    attestation: {
      title: string
      body: string[]
    }
  }
  concerns: {
    title: string
    headers: [string, string]
    items: ConcernItem[]
  }
  architecture: {
    title: string
    userBox: [string, string]
    runtimeLabel: string
    policyBox: [string, string, string]
    custodyBox: [string, string, string]
    hardwareLabel: string
  }
  differentiators: {
    title: string
    items: { bold: string; body: string }[]
  }
  disclaimer: string
}

export const teenetPageEn: TeenetPageContent = {
  meta: {
    title: 'TEENet Trust and Security | TEENet Secure Wallet',
    description: 'How TEENet protects your wallet with hardware-isolated execution, sharded key custody, and remote attestation.',
  },
  title: 'TEENet Trust and Security',
  backLink: '← Back to Home',
  whatIs: {
    title: 'What Is TEENet?',
    body: [
      'TEENet is a confidential-computing platform that runs applications inside hardware-protected environments called Trusted Execution Environments (TEEs). It combines a secure runtime with key custody — so private keys are generated, stored, and used entirely within hardware-isolated boundaries.',
      'No operator, cloud administrator, or external attacker can access keys or tamper with execution — even with physical access to the server.',
    ],
  },
  howProtects: {
    title: 'How TEENet Protects Your Wallet',
    hardware: {
      title: 'Hardware-Isolated Execution',
      body: [
        'Sensitive wallet logic — authorization checks, rule enforcement, signing — runs inside TEEs (Intel TDX, AMD SEV, ARM CCA). The CPU itself enforces isolation: memory is encrypted, code cannot be injected, and no external process can read or modify the execution state.',
        'This is not software sandboxing. It is hardware-level protection enforced by the processor.',
      ],
    },
    keys: {
      title: 'Keys Never Leave the TEE',
      body: [
        'Private keys are generated inside the TEE and never exported. They are sharded across multiple TEE nodes using MPC (Multi-Party Computation) and TSS (Threshold Signature Scheme). No single node ever holds a complete key.',
        'Signing requires a threshold of nodes to cooperate — and each node must be attested (verified by hardware) before participating.',
      ],
    },
    attestation: {
      title: 'Remote Attestation',
      body: [
        'Every TEE node proves its identity and integrity through hardware attestation. Before any node joins the network or participates in signing, it must present a cryptographic proof — generated by the CPU — that its software, configuration, and execution environment have not been tampered with.',
        'This proof is verified automatically. Trust is not assumed — it is measured and verified.',
      ],
    },
  },
  concerns: {
    title: 'What This Means for OpenClaw Wallet Users',
    headers: ['Concern', 'How TEENet Addresses It'],
    items: [
      { concern: 'Can my agent bypass approval rules?', answer: 'No. Rules are enforced inside the TEE. The agent cannot modify or skip them.' },
      { concern: 'Can an operator access my keys?', answer: 'No. Keys exist only inside hardware-encrypted memory. Operators have no access.' },
      { concern: 'Can a compromised server steal my keys?', answer: 'No. Keys are sharded across multiple TEE nodes. No single node holds a complete key.' },
      { concern: 'How do I know the runtime is genuine?', answer: 'Every node is verified by hardware attestation before it can participate. Trust is cryptographically proven.' },
      { concern: 'Can someone tamper with the signing logic?', answer: 'No. Code inside the TEE is measured and attested. Tampered code fails attestation and is rejected.' },
    ],
  },
  architecture: {
    title: 'Architecture Overview',
    userBox: ['User (OpenClaw)', 'Chat → Action → Approval (Passkey)'],
    runtimeLabel: 'TEE Trusted Runtime',
    policyBox: ['Policy Engine', 'Rules, Thresholds,', 'Contract Allowlists'],
    custodyBox: ['Key Custody Service', '(t-of-k threshold)', 'MPC/TSS sharded keys'],
    hardwareLabel: 'Hardware: Intel TDX / AMD SEV / ARM CCA',
  },
  differentiators: {
    title: 'Key Differentiators',
    items: [
      { bold: 'Not just an approval screen.', body: 'Many wallets add a confirmation dialog. TEENet enforces execution boundaries at the infrastructure level — rules cannot be bypassed by the application or the operator.' },
      { bold: 'Not just encryption.', body: 'Data encryption protects data at rest. TEENet protects data and logic during execution — the CPU itself prevents unauthorized access to running code and memory.' },
      { bold: 'Passkey beats multisig.', body: "Multisig means on-chain transactions, gas fees, and clunky coordination. TEENet replaces all of that with Passkey — biometric approval in seconds, off-chain inside the TEE, with zero gas cost." },
    ],
  },
  disclaimer: 'TEENet runtime is not open source. The application integration layer for OpenClaw is open. This page describes the trust and security properties of the TEENet platform as used by TEENet Secure Wallet.',
}

export const teenetPageZh: TeenetPageContent = {
  meta: {
    title: 'TEENet 信任与安全 | TEENet Secure Wallet',
    description: 'TEENet 如何通过硬件隔离执行、分片密钥托管和远程证明保护你的钱包。',
  },
  title: 'TEENet 信任与安全',
  backLink: '← 返回首页',
  whatIs: {
    title: '什么是 TEENet？',
    body: [
      'TEENet 是一个机密计算平台，在被称为可信执行环境（TEE）的硬件保护环境中运行应用。它将安全运行时与密钥托管相结合——私钥的生成、存储和使用完全在硬件隔离边界内完成。',
      '任何运维人员、云管理员或外部攻击者都无法访问密钥或篡改执行——即使拥有服务器的物理访问权限。',
    ],
  },
  howProtects: {
    title: 'TEENet 如何保护你的钱包',
    hardware: {
      title: '硬件隔离执行',
      body: [
        '敏感钱包逻辑——授权检查、规则执行、签名——在 TEE（Intel TDX、AMD SEV、ARM CCA）内运行。CPU 本身强制隔离：内存加密，代码无法注入，外部进程无法读取或修改执行状态。',
        '这不是软件沙箱，而是由处理器强制执行的硬件级保护。',
      ],
    },
    keys: {
      title: '密钥永不离开 TEE',
      body: [
        '私钥在 TEE 内生成，永不导出。它们通过 MPC（多方计算）和 TSS（门限签名方案）分片到多个 TEE 节点。没有任何单个节点持有完整密钥。',
        '签名需要达到门限数量的节点协作——每个节点必须在参与之前通过硬件证明（远程认证）。',
      ],
    },
    attestation: {
      title: '远程证明',
      body: [
        '每个 TEE 节点通过硬件证明来证实其身份和完整性。在任何节点加入网络或参与签名之前，它必须提交由 CPU 生成的加密证明——证明其软件、配置和执行环境未被篡改。',
        '该证明自动验证。信任不是假设的——它是被测量和验证的。',
      ],
    },
  },
  concerns: {
    title: '这对 OpenClaw 钱包用户意味着什么',
    headers: ['关注点', 'TEENet 的应对方式'],
    items: [
      { concern: '我的 Agent 能绕过审批规则吗？', answer: '不能。规则在 TEE 内执行。Agent 无法修改或跳过它们。' },
      { concern: '运维人员能访问我的密钥吗？', answer: '不能。密钥仅存在于硬件加密的内存中。运维人员无权访问。' },
      { concern: '被攻陷的服务器能窃取我的密钥吗？', answer: '不能。密钥分片到多个 TEE 节点。没有单个节点持有完整密钥。' },
      { concern: '我如何知道运行时是可信的？', answer: '每个节点在参与之前都经过硬件证明验证。信任是通过密码学证明的。' },
      { concern: '有人能篡改签名逻辑吗？', answer: '不能。TEE 内的代码经过度量和证明。被篡改的代码会无法通过证明验证而被拒绝。' },
    ],
  },
  architecture: {
    title: '架构概览',
    userBox: ['用户 (OpenClaw)', '对话 → 操作 → 授权 (Passkey)'],
    runtimeLabel: 'TEE 可信运行时',
    policyBox: ['策略引擎', '规则、阈值、', '合约白名单'],
    custodyBox: ['密钥托管服务', '(t-of-k 门限)', 'MPC/TSS 分片密钥'],
    hardwareLabel: '硬件: Intel TDX / AMD SEV / ARM CCA',
  },
  differentiators: {
    title: '关键差异',
    items: [
      { bold: '不只是审批弹窗。', body: '许多钱包只是添加确认对话框。TEENet 在基础设施层面强制执行边界——规则不能被应用或运维人员绕过。' },
      { bold: '不只是加密。', body: '数据加密保护静态数据。TEENet 在执行过程中保护数据和逻辑——CPU 本身阻止对运行中代码和内存的未授权访问。' },
      { bold: 'Passkey 胜过多签。', body: '多签意味着链上交易、Gas 费和繁琐的步骤。TEENet 用 Passkey 取代了这一切——生物识别秒级授权，在 TEE 内链下完成，零 Gas 成本。' },
    ],
  },
  disclaimer: 'TEENet 运行时不开源。面向 OpenClaw 的应用集成层是开放的。本页面描述 TEENet Secure Wallet 所使用的 TEENet 平台的信任与安全特性。',
}

export function getTeenetPageContent(locale: string): TeenetPageContent {
  return locale === 'zh' ? teenetPageZh : teenetPageEn
}
